version: "3"

services:
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password